### ISSUE TITLE
Dashboard IngressRoute not deleted

### ISSUE THREAD

**Issue by jasperkuperus** [containous/traefik-helm-chart#66] opened 2020-01-18 13:43 UTC
The `IngressRoute` of the dashboard is not deleted when you perform a `helm delete ...`. This probably got to do with the hook usage to install this ingress route, similar like this issue: https://github.com/containous/traefik-helm-chart/issues/22

**Comment by ldez** [comment] 2020-02-13 22:13
duplicate of #22

**Closed by ldez** 2020-02-13 22:13 UTC
Labels: duplicate
