### ISSUE TITLE
Encode query semicolons

### ISSUE THREAD

**Issue by kapilag123** [containous/traefik-helm-chart#892] opened 2023-07-21 14:26 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I can see PR https://github.com/traefik/traefik/pull/9943 is merged but it still not added in latest chart 23.1.0 . Can I use it in same chart or will be added in later version?

**Comment by ldez** [comment] 2023-07-21 14:36
related to #889

**Comment by mloiseleur** [comment] 2023-07-24 08:03
Hello @kapilag123,

Thanks for your interest in Traefik. 
The fix https://github.com/traefik/traefik/pull/9943 is available in Traefik Proxy 2.10.2
A new release of this chart should happen this week, after a new release of Traefik Proxy.
I close this issue since it's a duplicate of #886.

**Closed as completed by mloiseleur** 2023-07-24 08:03 UTC
Labels: resolution/duplicate, kind/bug/confirmed
