### ISSUE TITLE
Need basic things

### ISSUE THREAD

**Issue by cocktailer** [containous/traefik-helm-chart#198] opened 2020-06-13 06:28 UTC
1. Enable Web UI with basic auth
2. Enable Log
3. control on load balancer like name, etc.

**Comment by SantoDE** [comment] 2020-06-17 09:24
Hey @cocktailer,

I'll close that issue as its a duplicate of #185.

Could you please describe the need for #3 in that issue?

Thanks!

**Closed by SantoDE** 2020-06-17 09:24 UTC
