### ISSUE TITLE
Traefik stops being monitorable during graceTimeout

### ISSUE THREAD

**Issue by brianbraunstein** [containous/traefik-helm-chart#1202] opened 2024-09-27 21:53 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

v32.0.0

### What version of Traefik are you using?

default from the v32.0.0 helm chart

### What did you do?

I noticed that traefik is marked `up == 0` while `kube_pod_status_ready{condition="true"} == 0`

I debugged it to the helm chart not setting `requestAcceptGraceTimeout` properly for the metrics entrypoint/port (docs: https://doc.traefik.io/traefik/routing/entrypoints/#lifecycle).  It should be set here by default:
https://github.com/traefik/traefik-helm-chart/blob/7a13fc8a61a6ad30fcec32eec497dab9d8aea686/traefik/values.yaml#L707-L719

The default value for `graceTimeout` is 10 seconds according to https://doc.traefik.io/traefik/routing/entrypoints/#lifecycle , which means most people don't notice this bug.  However, we needed to increase `graceTimeout` for long lived connections so for long periods of time traefik becomes completely unmonitored, and appears down (`up == 0`) to our prometheus.

### What did you see instead?

I saw a bug

### What is your environment & configuration?

Traefik helm chart + kube + prometheus + long lived connections with `graceTimeout` set to a long value (hours).

**Comment by mloiseleur** [comment] 2024-10-04 09:56
At first glance, it seems more a configuration enhancement or warning to display than a real bug, but let's dig it.
Would you please share _values_ showing this issue you encountered ?

**Comment by mloiseleur** [comment] 2024-11-26 16:29
I'm closing this issse since there is no answer from @brianbraunstein 
Feel free to re-open it or open a new one if you need it, with steps detailing how to reproduce.

**Closed as completed by mloiseleur** 2024-11-26 16:29 UTC
Labels: contributor/need-more-information, kind/bug/possible
